// Copyright 2026 The go-subjectid Authors
// SPDX-License-Identifier: Apache-2.0

// genabnf reads the ABNF source files under ./abnf/ and emits a Go file
// containing one regexp.MustCompile per grammar. The output is the
// runtime library's compiled validator regex set; the library itself
// has no import on go-abnf.
//
// Invoke via `make gen-grammars` at the repo root; the Makefile cd's
// into this directory so the local tools/go.mod (separate from the
// library's go.mod) is in effect. The generated output path is set by
// the -out flag, defaulting to ../../grammars_gen.go.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	goabnf "github.com/pandatix/go-abnf"
)

// grammar pins one .abnf file to the top-level rule whose regex
// becomes a package-level var in the generated output. The varName
// is the Go identifier of the resulting *regexp.Regexp.
type grammar struct {
	file    string
	rule    string
	varName string
	rfc     string // spec reference for the doc comment on the var
}

var grammars = []grammar{
	{
		file:    "abnf/acct.abnf",
		rule:    "acct-uri",
		varName: "acctURIRe",
		rfc:     "RFC 7565 §3 acct URI",
	},
	{
		file:    "abnf/did.abnf",
		rule:    "did",
		varName: "didURLRe",
		rfc:     "W3C DID Core §3.1 did (top-level shell, no path/query/fragment)",
	},
	{
		file:    "abnf/phone.abnf",
		rule:    "phone",
		varName: "phoneE164Re",
		rfc:     "ITU-T E.164 basic international form",
	},
}

func main() {
	var outPath string
	flag.StringVar(&outPath, "out", "../grammars_gen.go", "path to write the generated file (default: ../grammars_gen.go)")
	flag.Parse()

	var body strings.Builder
	body.WriteString(`// Copyright 2026 The go-subjectid Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/genabnf. DO NOT EDIT.
//
// Regenerate with ` + "`make gen-grammars`" + ` from the repo root.
// CI verifies this file matches the ABNF inputs (see make check-gen).

package subjectid

import "regexp"

`)

	// Sort for deterministic output even if grammars list is reordered.
	sort.Slice(grammars, func(i, j int) bool {
		return grammars[i].varName < grammars[j].varName
	})

	for _, g := range grammars {
		abnfBytes, err := os.ReadFile(g.file)
		if err != nil {
			log.Fatalf("read %s: %v", g.file, err)
		}
		gr, err := goabnf.ParseABNF(abnfBytes)
		if err != nil {
			log.Fatalf("parse %s: %v", g.file, err)
		}
		regex, err := gr.Regex(g.rule)
		if err != nil {
			log.Fatalf("compile %q from %s: %v", g.rule, g.file, err)
		}

		fmt.Fprintf(&body, "// %s matches %s.\n", g.varName, g.rfc)
		fmt.Fprintf(&body, "// Source: %s (rule %q).\n", g.file, g.rule)
		fmt.Fprintf(&body, "var %s = regexp.MustCompile(`^(?:%s)$`)\n\n", g.varName, regex)
	}

	formatted, err := format.Source([]byte(body.String()))
	if err != nil {
		// Print the unformatted source so the failure is debuggable.
		_, _ = os.Stderr.WriteString(body.String())
		log.Fatalf("gofmt: %v", err)
	}

	abs, err := filepath.Abs(outPath)
	if err != nil {
		log.Fatalf("resolve %s: %v", outPath, err)
	}
	if err := os.WriteFile(abs, formatted, 0o644); err != nil {
		log.Fatalf("write %s: %v", abs, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", abs)
}
